spring.application.name=pdfConverter
# Set the maximum size allowed for a single uploaded file
spring.servlet.multipart.max-file-size=15MB

# Set the maximum size allowed for the entire request (in case you upload multiple files at once)
spring.servlet.multipart.max-request-size=25MB

server.port=${PORT:8080}